export const statusData = [
  {
    id: 'status-20260814',
    date: '2026.08.14',
    mood: '打工人的夏日实录',
    moodIcon: '🌙',
    category: 'daily',
    text: '工伤式上班：今天不完全统计，被蚊子咬了30多个包。内容人深入现场，首先深入的是草丛。',
    location: '北京 · 外拍现场',
    views: 520,
    likes: 38,
    comments: 12,
    replies: [{ author: '小鹿同学', text: '外拍辛苦了，夏天的草丛确实很有参与感。' }, { author: 'AI设计观察员', text: '内容人深入现场的第一课，先和蚊子打招呼。' }],
  },
  {
    id: 'status-20260808',
    date: '2026.08.08',
    mood: '片场临时身份已加载',
    moodIcon: '🎬',
    category: 'create',
    text: '来到八大之一的会计师事务所拍校招宣传片。今日身份：提词器主理人。看似站在屏幕后，实际掌握全场语速。',
    location: '校招宣传片现场',
    views: 486,
    likes: 56,
    comments: 8,
    replies: [{ author: '片场路人甲', text: '提词器主理人听起来已经掌握全场了！' }],
  },
  {
    id: 'status-20260801',
    date: '2026.08.01',
    mood: '主播营业中',
    moodIcon: '✨',
    category: 'create',
    text: '第一次进入专业直播间。表面：冷静讲解文创产品。内心：灯光老师能不能把“上镜胖十斤”这个设定关掉。希望今日直播顺利！',
    location: '中国国家地理探索直播间',
    image: '/media/status/status-2026-08-01.png',
    imageAlt: '中国国家地理探索直播间工作画面',
    views: 731,
    likes: 92,
    comments: 15,
    replies: [{ author: '文创收藏家', text: '主播上线，今天也要顺利营业！' }, { author: '小Xin的朋友', text: '上镜胖十斤这个设定申请永久关闭。' }],
  },
  {
    id: 'status-20260725',
    date: '2026.07.25',
    mood: '生日加载倒计时',
    moodIcon: '⭐',
    category: 'daily',
    text: '是哪个小女孩快过生日了？空间主人拒绝回答，但允许大家提前投递祝福。',
    views: 402,
    likes: 31,
    comments: 6,
    replies: [{ author: '空间访客520', text: '提前祝小女孩生日快乐，祝福已投递。' }],
  },
  {
    id: 'status-20260724',
    date: '2026.07.24',
    mood: '今天也在片场',
    moodIcon: '🎥',
    category: 'create',
    text: '假装是副导演的一天。对讲机没有拿反，流程表也还在手里，四舍五入就是专业人士。',
    location: '内容拍摄现场',
    views: 618,
    likes: 74,
    comments: 10,
    replies: [{ author: '导演组临时工', text: '对讲机没拿反，就是专业人士！' }, { author: '小蓝', text: '流程表在手，片场我有。' }],
  },
  {
    id: 'status-20260717',
    date: '2026.07.17',
    mood: 'AI实验有回音',
    moodIcon: '💡',
    category: 'ai',
    text: '今天拿员员子做了一个AI视频，流量还不错。认真复盘结论：技术负责把脑洞变成画面，可爱负责让大家停下来。',
    image: '/media/status/status-2026-07-17.png',
    imageAlt: 'AI视频角色下班主题画面',
    views: 888,
    likes: 126,
    comments: 19,
    replies: [{ author: 'AI实验室', text: '可爱负责让大家停下来，这个复盘很准确。' }, { author: '文化探索者', text: '想看更多员员子的AI实验！' }],
  },
  {
    id: 'status-20260711',
    date: '2026.07.11',
    mood: '入职前后的我',
    moodIcon: '💭',
    category: 'daily',
    text: '起初，不知道上班有多辛苦的我，还在勤劳健身。现在知道了，通勤本身就是有氧。',
    image: '/media/status/status-2026-07-11.png',
    imageAlt: '入职前在健身房运动的自拍',
    views: 344,
    likes: 28,
    comments: 5,
    replies: [{ author: '健身搭子', text: '通勤有氧认证通过，记得下班也要休息。' }],
  },
  {
    id: 'status-20260626',
    date: '2026.06.26',
    mood: '新地图加载成功',
    moodIcon: '📍',
    category: 'create',
    text: '叮——第一天入职！今日身份：中国国家地理新媒体运营实习生📍 正式进入内容世界。',
    location: '中国国家地理',
    views: 999,
    likes: 168,
    comments: 22,
    replies: [{ author: '互联网HR', text: '欢迎进入内容世界，期待你的新地图。' }, { author: '文化探索者', text: '第一天入职快乐，新的故事开始了！' }],
  },
]
